FROM debian:stretch-20170907

ENV DEBIAN_FRONTEND noninteractive
ENV LANG C.UTF-8

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y wget

RUN wget -O /usr/bin/jsteg https://github.com/lukechampine/jsteg/releases/download/v0.1.0/jsteg-linux-amd64
RUN chmod +x /usr/bin/jsteg

WORKDIR /data

CMD ["echo", "Hello world"]